### ISSUE TITLE
Can not build on MacOS arm64 from Release v2.24.0

### ISSUE THREAD

**Issue by SangTruongTan** [COVESA/dlt-viewer#367]
Hi,
I've just faced a problem when I tried to build the app for my MacOS. I think that there is a change between v2.23.0 and v2.24.0 (later on). It got the following error and I can by pass it by utilizing the static cast method.
Error:
```
Project/dlt-viewer/qdlt/qdltconnection.cpp:79:12: error: no viable conversion from 'QDltDataView' to 'QByteArray'
    data = dataView + bytes;
```
Remedy:
```
diff --git a/qdlt/qdltconnection.cpp b/qdlt/qdltconnection.cpp
index 20277fa..2534105 100644
--- a/qdlt/qdltconnection.cpp
+++ b/qdlt/qdltconnection.cpp
@@ -75,7 +75,7 @@ void QDltConnection::add(const QByteArray &bytes)
 {
     bytesReceived += bytes.size();
 
-    data = dataView + bytes;
+    data = static_cast<QByteArray>(dataView) + bytes;
```

**Comment by Hit2theMo** [comment]
Thanks a lot! This solved the same issue I faced.

**Comment by hannesa2** [comment]
Where exactly is you issue. I just created a new version https://github.com/COVESA/dlt-viewer/releases/tag/v2.25.0 and it builds for macOS, at least for x86

**Comment by SangTruongTan** [comment]
I'm using Apple Silicon, and it's also experienced on v2.25.0 again with the same point.

**Comment by hannesa2** [comment]
I applied this change in #369
<img width="617" alt="image" src="https://github.com/COVESA/dlt-viewer/assets/3314607/f6554263-d30d-4327-899d-8dc1a7fced55">

But locally on by M1 I still run into 
<img width="799" alt="image" src="https://github.com/COVESA/dlt-viewer/assets/3314607/b2bc2258-7957-4b49-bee8-49c711c59b44">

Even on CI https://github.com/COVESA/dlt-viewer/actions/runs/5839431094/job/15837605503?pr=369 it runs into the same error
<img width="767" alt="image" src="https://github.com/COVESA/dlt-viewer/assets/3314607/e96f6fc1-e3cd-4cb8-87ed-64deada7b4bd">

@SangTruongTan 
Please can you make a pull request to demonstrate, what exactly needs to be done ?

**Comment by SangTruongTan** [comment]
Hi @hannesa2,
It's very strange, that's the only change at my end. Did you try flushing cmake cache?

**Comment by hannesa2** [comment]
I did a `git clean -xdf`
What's your recommendation to flush cmake cache ? Maybe you should do this as well.

**Comment by SangTruongTan** [comment]
I believe it's a clean version I have just done it so far. The remedy is also working with @Hit2theMo.

**Comment by alexmucde** [comment]
Reopen as fix is not working.

**Comment by hannesa2** [comment]
> Please check at your end.

There is nothing to check on my send. Simple look at CI #369 and the resulting error

**Comment by SangTruongTan** [comment]
Fixed by the remedy: https://github.com/COVESA/dlt-viewer/pull/373/commits/4bb3b26802316cd3fa28fde92f1ea32a72070fa3
